apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fim
  namespace: fim
subjects:
- kind: User
  name: fim
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io